name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-50
    steps:
      - uses: actions/checkout@v4
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@master
        with:
          manifest-path: io.github.NikolausB.WorkoutTimer.yml
          run-tests: true